### PR TITLE
Adding files to accompany FFR manuscript (under review at AoAS)

### PR DESCRIPTION
**Pull request by mzemplenyi**

### CODE REVIEW

**Comment by mzemplenyi** [comment]
@Jeffrey-S-Morris, could you take a look at this pull request when you get a chance? Thank you!

**Comment by Jeffrey-S-Morris** [comment]
Is it good to go?

**Comment by mzemplenyi** [comment]
Yes, that worked - thank you!

**Comment by Jeffrey-S-Morris** [comment]
Great!

Sent from my iPhone

On Jul 24, 2020, at 5:41 PM, mzemplenyi <notifications@github.com> wrote:

﻿

Yes, that worked - thank you!

**Pull request merged**
